### ISSUE TITLE
Possible README Typo 

### ISSUE THREAD

**Issue by BolajiOlajide** [whizkydee/react-multi-state#1]
Hey Olaolu,

I noticed the README for this project contains a code sample that might not be accurate so I decided to bring it to your attention. 

It's around [here](https://github.com/whizkydee/react-multi-state#-comparison-with-reactusestate-examples),  I noticed the variable `state` doesn't exist and you were mutating it.

The code snippet is shown below:

```js
import React, { useState, useEffect } from 'react'

export default function Users() {
  const [users, setUsers] = useState([])
  const [userName, setUserName] = useState('')
  const [gender, setGender] = useState('M')
  const [isFetched, setIsFetched] = useState(false)

  useEffect(() => {
    ;(async function() {
      const usersData = await getUsers()
      state.users = usersData
      state.isFetched = true
    })()
  }, [])
}```

but I believe it should be

```js
import React, { useState, useEffect } from 'react'

export default function Users() {
  const [users, setUsers] = useState([])
  const [userName, setUserName] = useState('')
  const [gender, setGender] = useState('M')
  const [isFetched, setIsFetched] = useState(false)

  useEffect(() => {
    ;(async function() {
      setIsFetched(true)
      const usersData = await getUsers()
      setUsers(usersData)
      setIsFetched(false)
    })()
  }, [])
}
```

I might be wrong here but I thought to bring it up, before sending a PR for this. cc @whizkydee

**Comment by whizkydee** [comment]
Thanks, man. Unfortunately, I don't see the typo here. Maybe I'm missing something?

**Comment by BolajiOlajide** [comment]
Good job creating this by the way.

**Comment by BolajiOlajide** [comment]
@whizkydee Sorry I hadn't finished typing and mistakenly hit enter.
Just updated the issue.

**Comment by whizkydee** [comment]
Haha, I see that! Copy-paste error, will fix now. Thanks!
