### ISSUE TITLE
Write typings for useMultiState

### ISSUE THREAD

**Issue by whizkydee** [whizkydee/react-multi-state#2]

**Comment by Lagily** [comment]
would be great to have this - do you have any ideas on how to supply types for the returned setters? Because they are dynami 'set' + prop.name it can be quite the challenge I would imagine.

**Comment by whizkydee** [comment]
Yeah, it's pretty much done. Unfortunately, TypeScript doesn't have an API that lets you dynamically compose object property names. There's an open feature request for it since 2016: microsoft/TypeScript/issues/12754

**Comment by Lagily** [comment]
I see, I was thinking something like this might be good enough, at least all properties of the setters would be functions then:

`export default function useMultiState<T>(initialState: T): [T, (newState: Partial<T>) => void, { [key: string]: Function }];`

I'll send a PR if you want

**Comment by whizkydee** [comment]
Sure, go ahead!
